add mostRecentStatusDate
datafiniti/default-views pull request #4
Opened 2019-09-07 01:57 UTC by trobe026

2019-09-09 17:44 UTC, hessmjr requested changes
don't we need to add statuses.date as well?

2019-09-09 20:42 UTC, trobe026 commented
@hessmjr  Statuses isn't broken up into subfields the way prices and reviews are currently. Does it need to be?

2019-09-11 20:40 UTC, hessmjr commented
@trobe026 there is a doc on how to update default views on Infra's confluence, can you add that to the PR template?

2019-09-11 22:58 UTC, hessmjr approved these changes

2019-09-11 22:58 UTC, merged